Repository rajdeep13-coder/Resume-Generator, pull requests merged in 2025-07, with the labels that each got.

#28 Modified Toggle(sun/moon icon) along with LocalStorage
  index.html
  script.js
  style.css
Labels: enhancement, gssoc25, level2

#30 Implement Live Character Count for Professional Summary
  index.html
  script.js
  style.css
Labels: gssoc25, level2

#35 Fixed the footer with a clean UI
  index.html
  style.css
Labels: gssoc25, level2

#41 Add Input Field Validation for Resume Details
  index.html
  script.js
  style.css
Labels: gssoc25, level2

#59 Add mit license file to the
  License.md
Labels: documentation, gssoc25

#68 feat: add bottombar scroll-to-top icon #63
  index.html
  script.js
  style.css
Labels: enhancement, gssoc25, level2
