Repository rajdeep13-coder/Resume-Generator, pull requests merged in 2025-08, with the labels that each got.

#86 Added Code of Conduct file
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, gssoc25

#85 Added Grammar Check and SpellCheck using API
  index.html
  script.js
  style.css
Labels: enhancement, gssoc25, level3

#92 Fixed validation logic and download behavior
  script.js
Labels: bug, gssoc25

#108 input box css changed
  style.css
Labels: gssoc25, level2
